[package]
name = "barnacleboy_macros"
version = "0.1.0"
authors = ["Wesley Norris <repnop@outlook.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
syn = { version = "0.15.21", features = ["full"] }
quote = "0.6.10"
proc-macro2 = "0.4.24" 